<?php //root\app\design\frontend\default\default\template\pro\form.phtml ?>
<fieldset class="form-list">
    <?php $_code=$this->getMethodCode() ?>
    <ul id="payment_form_<?php echo $_code ?>" style="display:none">
        <li>
            <?php echo $this->__('You will be redirected to the PayU&trade; website to enter your payment details when you complete the order.') ?>
        </li>
    </ul>
</fieldset>